# Generated by Django 5.1.1 on 2024-10-17 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id_borrower', models.AutoField(primary_key=True, serialize=False)),
                ('Username_borrower', models.CharField(max_length=50)),
                ('Name_borrower', models.CharField(max_length=100)),
                ('Firstname_borrower', models.CharField(max_length=50)),
                ('Middlename_borrower', models.CharField(max_length=50)),
                ('Firstsurname_borrower', models.CharField(max_length=50)),
                ('Secondsurname_borrower', models.CharField(max_length=50)),
                ('BirthDate_borrower', models.DateField()),
                ('Email_borrower', models.CharField(max_length=100)),
                ('Password_borrower', models.CharField(max_length=60)),
                ('Phonenumber_borrower', models.CharField(max_length=10)),
                ('RFC_borrower', models.CharField(max_length=13)),
                ('CIEC_borrower', models.CharField(max_length=100)),
                ('Fulladdress_borrower', models.CharField(max_length=200)),
                ('City_borrower', models.CharField(max_length=50)),
                ('neighboorn_borrower', models.CharField(max_length=50)),
                ('CP_borrower', models.CharField(max_length=5)),
                ('State_borrower', models.CharField(max_length=50)),
                ('Country_borrower', models.CharField(max_length=50)),
                ('PossibilityOfPay', models.FloatField()),
                ('ScoreLlamas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceHistory',
            fields=[
                ('ID_invoice', models.AutoField(primary_key=True, serialize=False)),
                ('UUID', models.CharField(max_length=100)),
                ('Download_date', models.DateField()),
                ('CFDI_date', models.DateField()),
                ('Timbre_date', models.DateField()),
                ('Cancellation_date', models.DateField(null=True)),
                ('Status_date', models.DateField()),
                ('Issuing_party', models.CharField(max_length=100)),
                ('Receiving_party', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Total', models.FloatField()),
                ('Acuse', models.BooleanField()),
                ('Invoice_pay', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('ID_Loan', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.FloatField()),
                ('Difficulty', models.IntegerField()),
                ('InterestRate', models.FloatField()),
                ('PaymentTerm', models.DateField()),
                ('Amortization', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Moneylender',
            fields=[
                ('id_Moneylender', models.AutoField(primary_key=True, serialize=False)),
                ('Username_Moneylender', models.CharField(max_length=50)),
                ('Name_Moneylender', models.CharField(max_length=100)),
                ('Firstname_Moneylender', models.CharField(max_length=50)),
                ('Middlename_Moneylender', models.CharField(max_length=50)),
                ('Firstsurname_Moneylender', models.CharField(max_length=50)),
                ('Secondsurname_Moneylender', models.CharField(max_length=50)),
                ('BirthDate_Moneylender', models.DateField()),
                ('Email_Moneylender', models.CharField(max_length=100)),
                ('Password_Moneylender', models.CharField(max_length=60)),
                ('Phonenumber_Moneylender', models.CharField(max_length=10)),
                ('RFC_Moneylender', models.CharField(max_length=13)),
                ('CIEC_Moneylender', models.CharField(max_length=100)),
                ('Fulladdress_Moneylender', models.CharField(max_length=200)),
                ('City_Moneylender', models.CharField(max_length=50)),
                ('neighboorn_Moneylender', models.CharField(max_length=50)),
                ('CP_Moneylender', models.CharField(max_length=5)),
                ('State_Moneylender', models.CharField(max_length=50)),
                ('Country_Moneylender', models.CharField(max_length=50)),
                ('Subscription_Moneylender', models.BooleanField()),
                ('LoansActive_Moneylender', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id_check', models.AutoField(primary_key=True, serialize=False)),
                ('date_account_open', models.DateField()),
                ('actual_balance', models.FloatField()),
                ('max_credit', models.FloatField()),
                ('lim_credit', models.FloatField()),
                ('pay_history', models.CharField(max_length=50)),
                ('current_pay_status', models.CharField(max_length=10)),
                ('accounts_open', models.IntegerField()),
                ('accounts_closed', models.IntegerField()),
                ('account_fixed_payment', models.BooleanField()),
                ('num_mop1', models.IntegerField()),
                ('num_mop2', models.IntegerField()),
                ('num_mop3', models.IntegerField()),
                ('num_mop4', models.IntegerField()),
                ('num_mop5', models.IntegerField()),
                ('num_mop6', models.IntegerField()),
                ('num_mop7', models.IntegerField()),
                ('check_date', models.DateField()),
                ('code_score', models.FloatField()),
                ('place_of_work', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.borrower')),
            ],
        ),
        migrations.AddField(
            model_name='borrower',
            name='invoice_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.invoicehistory'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.loans'),
        ),
        migrations.AddField(
            model_name='loans',
            name='ID_Moneylender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.moneylender'),
        ),
        migrations.CreateModel(
            name='ActiveLoans',
            fields=[
                ('IDLoanActive', models.AutoField(primary_key=True, serialize=False)),
                ('TotalDebt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalDebtPay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AmountToPay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DayOfPay', models.DateField()),
                ('PastDueBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.borrower')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.loans')),
                ('moneylender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.moneylender')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('ID_Transaction', models.AutoField(primary_key=True, serialize=False)),
                ('AmountPaid', models.FloatField()),
                ('PaymentDate', models.DateTimeField(auto_now_add=True)),
                ('PayPalTransactionID', models.CharField(max_length=100, unique=True)),
                ('Status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=20)),
                ('TransactionType', models.CharField(choices=[('payment', 'Payment'), ('payout', 'Payout')], max_length=10)),
                ('ID_ActiveLoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.activeloans')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False)),
                ('Borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.borrower')),
                ('Usercheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.credithistory')),
                ('moneylender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.moneylender')),
            ],
        ),
    ]
