# Generated by Django 5.1.1 on 2024-10-19 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('first_surname', models.CharField(max_length=50)),
                ('second_surname', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=10)),
                ('rfc', models.CharField(max_length=13)),
                ('ciec', models.CharField(max_length=100)),
                ('full_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=50)),
                ('cp', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('possibility_of_pay', models.FloatField()),
                ('score_llamas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=100)),
                ('download_date', models.DateField()),
                ('cfdi_date', models.DateField()),
                ('timbre_date', models.DateField()),
                ('cancellation_date', models.DateField(null=True)),
                ('status_date', models.DateField()),
                ('issuing_party', models.CharField(max_length=100)),
                ('receiving_party', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acuse', models.BooleanField()),
                ('invoice_pay', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('difficulty', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_term', models.DateField()),
                ('amortization', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Moneylender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_surname', models.CharField(max_length=50)),
                ('second_surname', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=15)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('ciec', models.CharField(max_length=100)),
                ('full_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('active_loans', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_account_open', models.DateField()),
                ('actual_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lim_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_history', models.CharField(max_length=50)),
                ('current_pay_status', models.CharField(max_length=10)),
                ('accounts_open', models.IntegerField()),
                ('accounts_closed', models.IntegerField()),
                ('account_fixed_payment', models.BooleanField()),
                ('num_mop1', models.IntegerField()),
                ('num_mop2', models.IntegerField()),
                ('num_mop3', models.IntegerField()),
                ('num_mop4', models.IntegerField()),
                ('num_mop5', models.IntegerField()),
                ('num_mop6', models.IntegerField()),
                ('num_mop7', models.IntegerField()),
                ('check_date', models.DateField()),
                ('code_score', models.FloatField()),
                ('place_of_work', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.borrower')),
            ],
        ),
        migrations.AddField(
            model_name='borrower',
            name='invoice_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.invoicehistory'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.loan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='moneylender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.moneylender'),
        ),
        migrations.CreateModel(
            name='ActiveLoan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_debt_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day_of_pay', models.DateField()),
                ('past_due_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.borrower')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.loan')),
                ('moneylender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.moneylender')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.borrower')),
                ('credit_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.credithistory')),
                ('moneylender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.moneylender')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.FloatField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('paypal_transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('payout', 'Payout')], max_length=10)),
                ('active_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.activeloan')),
            ],
        ),
    ]
