# Generated by Django 5.1.1 on 2024-10-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credithistory',
            name='val_score',
            field=models.IntegerField(default=0),
        ),
    ]
