# Generated by Django 5.1.1 on 2024-10-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_loan_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='ActiveLoan',
            new_name='active_loan',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='Number_of_pay',
            new_name='number_of_pay',
        ),
    ]
