# Generated by Django 5.1.1 on 2024-11-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_payments_active_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credithistory',
            name='account_fixed_payment',
        ),
        migrations.RemoveField(
            model_name='credithistory',
            name='check_date',
        ),
        migrations.RemoveField(
            model_name='credithistory',
            name='current_pay_status',
        ),
        migrations.RemoveField(
            model_name='credithistory',
            name='pay_history',
        ),
        migrations.RemoveField(
            model_name='credithistory',
            name='place_of_work',
        ),
        migrations.RemoveField(
            model_name='credithistory',
            name='salary',
        ),
    ]
