# Generated by Django 5.1.1 on 2024-10-25 23:58
# Generated by Django 5.1.1 on 2024-10-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_borrower_personafom_borrower_exteriornumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='PersonaFoM',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='exteriorNumber',
        ),
        migrations.AddField(
            model_name='moneylender',
            name='municipality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='moneylender',
            name='nationality',
            field=models.CharField(default='MX', max_length=50),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='municipality',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
