# Generated by Django 5.1.1 on 2024-10-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_borrowerscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerscore',
            name='code_score',
            field=models.IntegerField(),
        ),
    ]
