# Generated by Django 5.1.1 on 2024-10-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_borrowerscore_code_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerscore',
            name='code_score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='borrowerscore',
            name='val_score',
            field=models.CharField(max_length=10),
        ),
    ]
