# Generated by Django 5.1.1 on 2024-10-28 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_borrowerscore_code_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeloan',
            name='day_of_pay',
        ),
        migrations.RemoveField(
            model_name='activeloan',
            name='past_due_balance',
        ),
        migrations.RemoveField(
            model_name='activeloan',
            name='total_debt',
        ),
        migrations.AddField(
            model_name='activeloan',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='duration_loan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Number_of_pay', models.IntegerField()),
                ('date_to_pay', models.DateField()),
                ('paid', models.BooleanField(null=True)),
                ('paid_on_time', models.BooleanField(null=True)),
                ('ActiveLoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.activeloan')),
            ],
        ),
        migrations.DeleteModel(
            name='BorrowerScore',
        ),
    ]
